### ISSUE TITLE
XMouse Button Control and BuildVision 3.0 are not playing nice

### ISSUE THREAD

**Issue by mitoskalandiel** [ZachHembree/BuildVision2#1]
I use XMouse Button Control to remap my mouse wheel to use "natural" scrolling, and unfortunately BuildVision will not appear in game, unless I kill XMBC completely. I realize this may be the wrong repo to address, but I would like guidance on what could be going wrong here.

It may help to understand this better knowing that the remapping of the mouse wheel is NOT translated into SE (with XMBC open), so SE must be handling mouse wheel actions differently than other apps..

**Comment by ZachHembree** [comment]
I've been able to reproduce this issue on my end, but I'm afraid the problem extends to the raw input data provided by the game's input handling system. I've not determined what the root cause is, exactly, but it appears that the input interface will not update the scroll wheel position if either Ctrl or Shift (but not Alt) are held while invert scroll is enabled in XMBC. 

So long as either of those keys are pressed, the raw input value reported by the API stays the same. Consequently, the software can't actually see if the scroll wheel is moving. Since this only happens when used in combination with those keys, I'm inclined to think this has to do with some sort of setting or bug in XMBC, rather than SE, but I'm not familiar with the software, so I can't say with any certainty.

**Comment by mitoskalandiel** [comment]
dude, you've done me a solid already giving me such a detailed root-cause analysis from your end, thanks a lot, it's something I can take up (maybe) with the dev of XMBC

**Comment by mitoskalandiel** [comment]
I have found a fix for this, btw:

* Add SpaceEngineers as new profile under XBMC (when asked, point it to your SE executable or select it from your running tasks if it's open)
* Under Tab "Scrolling" Set Scroll Method to "Method 4 (Wheel Msg)"

These are the settings after setup, and I've confirmed this working on latest SE with BV 3.0 and extra Build Info
![image](https://user-images.githubusercontent.com/8307871/197341150-b2b106d6-3e50-43a1-bd00-359a4b239ae6.png)
